src/main/kotlin/gg/essential/universal/wrappers/message/UTextComponent.kt
UTextComponent's hover value has a type of Any? but performs an unchecked cast on all cases to String.
Appending any MCITextComponent causes a ClassCastException because a MCITextComponent is passed
=> UTextComponent: Fix appending text components with hover events

src/main/kotlin/gg/essential/universal/wrappers/message/UMessage.kt
This pr removes the TODO left behind by searching for the `printChatMessageWithOptionalDeletion` method (or `addMessage` on newer versions) via method signature.
=> UMessage: Expose `printChatMessageWithOptionalDeletion` on newer versions via reflection

src/main/kotlin/gg/essential/universal/wrappers/message/UMessage.kt
The current implementation of the method handle does not provide the correct signature. 
It's given `(UTextComponent,I)Object` when it wants `(GuiNewChat,MCITextComponent,I)V`
=> Fix Method Handle Invocation

api/UniversalCraft.api, src/main/java/gg/essential/universal/UGraphics.java, src/main/kotlin/gg/essential/universal/utils/ReleasedDynamicTexture.kt, versions/1.15.2-1.12.2.txt
When [creating the MC-independent UC jar]( https://github.com/EssentialGG/essential-gradle-toolkit#stripreferencestransform) used for compiling the version-independent parts of Elementa, any types from MC and all methods referencing these are omitted (so you can't accidentally use version-dependent things).
There are a few common methods used all over Elementa though, and none of these are really MC-specific, so this PR adds MC-independent variants for those.
The removals in the API file aren't actual removals, those entries just got reordered because the algorithm, which merges the api files from the different versions, isn't perfectly stable wrt to surrounding entries.
=> Add miscelaneous MC-independent methods

src/main/kotlin/gg/essential/universal/UDesktop.kt
Using quotes in the `open` command causes it to not open the URL.
Removing the quotes around the URL allows any URL to open correctly.
I have recorded a [video](https://streamable.com/al0qfr) to demonstrate this. This has also been tested in my mod environment and works as expected now.
*This supersedes #14*
=> UDesktop: don't use quotes when opening URLs on macOS + Linux & use a vararg for `runCommand`

api/UniversalCraft.api, src/main/kotlin/gg/essential/universal/UImage.kt, src/main/kotlin/gg/essential/universal/utils/typealises.kt
Rather than only in Essential, this would be more useful here.
Additions include getters for width and height, a setter for pixel RGB, and a copy method to create a new instance of a UImage.
The only other change is get was renamed to getPixelRGB for clarity.
=> Add UImage

src/main/kotlin/gg/essential/universal/UKeyboard.kt
Otherwise, a call to isKeyDown that is out of range will throw an `ArrayIndexOutOfBoundsException`. Fixes EM-492.
=> UKeyboard: Ensure key index is within the valid range of the keyboard on LWJGL2

src/main/kotlin/gg/essential/universal/UDesktop.kt
Trying to detect the executable we should be using merely by looking at
environment variables fails under various circumstance, e.g. env vars may be set
inside a flatpack but the command isn't necessarily available in there; more
generally just because a particular DE is in used, doesn't guarantee that the
corresponding package is installed.
This commit addresses this issue by simply trying all executables in preferred
order until one of them succeeds.
=> UDesktop: Improve browser/open/edit linux compatibility 

api/UniversalCraft.api, src/main/kotlin/gg/essential/universal/UMatrixStack.kt
UniversalCraft generally makes for a pretty good abstraction of a significant
chunk of Minecraft, such that one can write code which is only compiled once but
works with all versions of Minecraft.
Such code however cannot access the model matrix of a UMatrixStack because its
type is `Matrix4f` which is a Minecraft type that changes across version.
This commit provides an accessor to retrieve the content of the matrix in a
version independent way (plain old FloatArray).
=> UMatrixStack: Add version-independent model matrix accessor

src/main/kotlin/gg/essential/universal/UMatrixStack.kt
Modern MC has two global storage locations for matrices, the global model view stack (`RenderSystem.getModelViewStack`) and the currently active matrix (set via `RenderSystem.applyModelViewMatrix` which copies from the top of the aforementioned stack).
`UMatrixStack`'s `applyToGlobalState` is meant to apply in such a way that the user can immediately make use of the applied global state (i.e. it should apply to both global MC storage locations), however the current implementation calls `applyModelViewMatrix` too early, after pushing MC's global stack but before applying the top of the `UMatrixStack` to it.
This commit fixes that by moving the `applyModelViewMatrix` call to right after the multiplication which put our head on top of the vanilla stack.
=> UMatrixStack: Fix `applyModelViewMatrix` being called too early

src/main/java/gg/essential/universal/UGraphics.java
We store default shaders for each built-in vertex format in a `HashMap`. Turns out though that `VertexFormat`'s `equals` implementation is broken and returns true for two `VertexFormat`s that use the same elements but in a different order (such as PosTexColorLight vs PosTexLightColor). As a result if you tried to draw the former, it'd actually use the shader for the latter and misinterpret your light texture coordinates as the vertex color and vice versa, usually producing invalid or simply no visible output.
=> UGraphics: Fix incorrect default shader being used

api/UniversalCraft.api, src/main/java/gg/essential/universal/UGraphics.java, src/main/kotlin/gg/essential/universal/shader/UShader.kt, versions/1.17.1-fabric/src/main/kotlin/gg/essential/universal/shader/MCShader.kt
This is necessary in order for shaders to work correctly on 1.17+. Previously, only simple shaders were tested which happened to match the order of replaceAttribute calls, so this issue went unnoticed.
=> MCShader: sort attributes according to VertexFormat

.github/workflows/main.yml, gradle.properties, root.gradle.kts, settings.gradle.kts, versions/1.16.2-1.12.2.txt, versions/1.16.2-1.15.2.txt
Also removes 1.15 because of a bug in archloom ([1]).
Diff between 1.16.2-forge before and after the removal shows no significant
changes:
<details>
```diff
diff -r org/main/java/gg/essential/universal/UGraphics.java versions/1.16.2-forge/build/preprocessed/main/java/gg/essential/universal/UGraphics.java
55,58c55,58
< //$$ import net.minecraft.client.renderer.Matrix3f;
< //$$ import net.minecraft.client.renderer.Matrix4f;
< //$$ import net.minecraft.client.renderer.Vector3f;
< //$$ import net.minecraft.client.renderer.Vector4f;
---
> //$$ import org.lwjgl.util.vector.Matrix3f;
> //$$ import org.lwjgl.util.vector.Matrix4f;
> //$$ import org.lwjgl.util.vector.Vector3f;
> //$$ import org.lwjgl.util.vector.Vector4f;
diff -r org/main/kotlin/gg/essential/universal/vertex/VanillaVertexConsumer.kt …
```
=> Build: Enable GitHub Actions based CI

.github/workflows/main.yml, api/UniversalCraft.api, root.gradle.kts, settings.gradle.kts, src/main/kotlin/gg/essential/universal/UScreen.kt, src/main/kotlin/gg/essential/universal/wrappers/UPlayer.kt, versions/1.20.2-fabric/gradle.properties
=> Build: Port to 1.20.2-rc2 Fabric

.github/workflows/main.yml, settings.gradle.kts
There were at least two (potentially more that were fixed by Loom 1.2 -> 1.3 update) issues that are fixed in this commit:
1. `~` does not expand inside `"`, unlike regular variables. As such the maximum heap size wasn't actually applied and instead Gradle was free to consume all the memory in the VM, eventually killing the actions runner, resulting in fairly unhelpful failure messages.
2. A workaround for the BuildSharedServiceManager issue has been applied in Essential Loom 1.3.12. With that, it now easily builds in a single pass.
=> Build: Fix GitHub Actions out-of-memory issues

versions/1.20.2-fabric/gradle.properties
essential-gradle-toolkit has been updated to provide 1.20.2 defaults in a previous commit.
=> Build: Bump to 1.20.2 Fabric (from -rc2)

versions/1.17.1-fabric/src/main/kotlin/gg/essential/universal/shader/MCShader.kt
This ensures that shader attributes are bound correctly. Shader calls glBindAttributeLocation using the names in the VertexFormat, not the names in the shader json. By constructing a custom VertexFormat, we can get around this.
=> MCShader: use transformed attribute names in VertexFormat for Shader

src/main/kotlin/gg/essential/universal/UScreen.kt
The contract for UScreen has always been that the user needs to explicitly call `onDrawBackground` from their `onDrawScreen` override if they want their screen to have a background; that's how it used to work in Minecraft prior to 1.20.2.
As of 1.20.2, `Screen.render` (called by `onDrawScreen`) now also draws the background in addition to vanilla elements, as such the background is drawn twice; and if a custom screen wishes to not have any background, it's draw anyway.
This commit fixes that by suppressing the vanilla background method call when it happens within our `super.render` call. That way users retain control over the background, and in a way that's consistent across versions.
Linear: EM-2544
=> UScreen: Fix background being drawn twice on 1.20.2+

build.gradle.kts
Closes #70
This corrects the library being incorrectly labelled as a `LIBRARY` and thus breaking usage with Sinytra Connector.
~~`LIBRARY` does not have access to minecraft classes because it is in the plugin layer. `GAMELIBRARY` is in the game layer so it can access minecraft classes.~~
Source: [SpongePowered/Sponge#3898](https://github.com/SpongePowered/Sponge/pull/3898)
=> Fix library being incorrectly declared as a `LIBRARY`

api/UniversalCraft.api, src/main/java/gg/essential/universal/UGraphics.java, src/main/kotlin/gg/essential/universal/UI18n.kt, src/main/kotlin/gg/essential/universal/UMinecraft.kt
Once these are part of UC, Elementa and Vigilance will no longer have any direct MC dependencies, allowing us to publish only a single version each, instead of having to publish one per MC-version/mod loader as we do right now.
(Not sure why the `getFontRenderer` api entries moved, but they were indeed improperly sorted before.)
=> Misc: Add remaining methods used by Elementa and Vigilance

src/main/java/gg/essential/universal/UGraphics.java, src/main/kotlin/gg/essential/universal/UImage.kt, src/main/kotlin/gg/essential/universal/UKeyboard.kt, src/main/kotlin/gg/essential/universal/UMatrixStack.kt, src/main/kotlin/gg/essential/universal/UMinecraft.kt, src/main/kotlin/gg/essential/universal/shader/UShader.kt, src/main/kotlin/gg/essential/universal/wrappers/UPlayer.kt, src/main/kotlin/gg/essential/universal/wrappers/message/UTextComponent.kt, versions/1.17.1-fabric/src/main/kotlin/gg/essential/universal/shader/MCShader.kt, versions/1.19.3-fabric/src/main/kotlin/gg/essential/universal/DummyPack.kt
(The gradle deprecation warnings I'll deal with another time; one of them also appears to be a Gradle bug, so we're not getting rid of them completely anyway.)
=> Misc: Cleanup warnings

src/main/java/gg/essential/universal/UGraphics.java
The `GlStateManager.bindTexture` calls were erroneously changed to `UGraphics.bindTexture` in 13c00ee9, however that method on 1.17+ does not actually bind the texture on the OpenGL level anymore, it only sets MC's global field which is insufficient for `configureTexture`.
=> UGraphics: Fix regression in configureTexture

standalone/build.gradle.kts, standalone/example/src/main/kotlin/gg/essential/example/main.kt, standalone/src/main/resources/log4j2.xml
We use version 2 of slf4j, so we need to include the log4j adapter which was built for version 2, not the one for version 1.
With that, logging works, but it's using log4j's ugly default format and only emits WARN or above.
To improve the out-of-the-box behavior for Standalone UC, we add a default log4j config file; applications which require further customization can override it via one of the many way which log4j provides.
=> Standalone: Fix slf4j logging and add default log4j config

api/UniversalCraft.api, src/main/java/gg/essential/universal/UGraphics.java
For use from MC-independent code, and easier use across versions (specifically 1.21.5).
(this already includes the 1.21.5 case because it happens to match the case required for the `:standalone` UC version which uses `MC==99999` and so is served by `>=12105`)
=> UGraphics: Add `clearColor` and `clearDepth`

api/UniversalCraft.api, src/main/kotlin/gg/essential/universal/UChat.kt, src/main/kotlin/gg/essential/universal/UKeyboard.kt, src/main/kotlin/gg/essential/universal/UPacket.kt, src/main/kotlin/gg/essential/universal/utils/textUtils.kt, src/main/kotlin/gg/essential/universal/wrappers/UPlayer.kt, src/main/kotlin/gg/essential/universal/wrappers/message/UMessage.kt, src/main/kotlin/gg/essential/universal/wrappers/message/UTextComponent.kt, standalone/src/main/kotlin/gg/essential/universal/utils/textUtils.kt
Porting it to 1.21.5 while maintaining its API is difficult (actions are no longer separate from their values and those are no longer stringly typed either).
As such, this commit deprecates the class as well as the closely adjacent (and also badly designed) `UMessage` class.
For methods which are still generally useful, it introduces overloads which take the vanilla component.
`UChat.chat` was already taking `Any`, so `String` and vanilla components can simply be passed to it directly.
It also moves out the code which turns the component into a plain (formatted or unformatted) string into separate utilities because that is still very much useful (and about the only justified use-case of UTextComponent in Essential).
The only significant loss is the ability of `UMessage` to edit messages …
=> UTextComponent: Deprecate

build.gradle.kts, src/main/kotlin/gg/essential/universal/shader/UShader.kt, src/main/kotlin/gg/essential/universal/vertex/UVertexConsumer.kt
Instead generating the compatibilty stubs necessary for maintaining binary compatibility on 1.12.2 and 1.8.9 via annotations on the two affected interfaces.
This way any newly introduced interfaces won't have to have the compatibility stubs any more.
Also bumps our Kotlin dependency from 1.5 to 1.6 because `JvmDefaultWithCompatibility` was only introduced in 1.6.
For details on all the jvmdefault options, see https://kotlinlang.org/docs/java-to-kotlin-interop.html#compatibility-modes-for-default-methods.
=> Build: Switch to `-Xjvmdefault=all` for all versions

src/main/kotlin/gg/essential/universal/UResolution.kt
re: https://linear.app/essential/issue/EM-3153/the-background-has-been-scaled-several-times-under-the-dragged
=> add additional values to `ScaledResolutionInputs` to better detect when other mods have modified gui scaling

api/UniversalCraft.api, root.gradle.kts, settings.gradle.kts, src/main/java/gg/essential/universal/UGraphics.java, src/main/kotlin/gg/essential/universal/UMatrixStack.kt, src/main/kotlin/gg/essential/universal/UResolution.kt, src/main/kotlin/gg/essential/universal/UScreen.kt, src/main/kotlin/gg/essential/universal/render/ScissorState.kt, src/main/kotlin/gg/essential/universal/render/URenderPass.kt, src/main/kotlin/gg/essential/universal/render/URenderPipeline.kt, src/main/kotlin/gg/essential/universal/shader/ShaderTransformer.kt, src/main/kotlin/gg/essential/universal/utils/ReleasedDynamicTexture.kt, versions/1.21.6-fabric/gradle.properties, versions/1.21.6-fabric/src/main/kotlin/gg/essential/universal/AdvancedDrawContext.kt, versions/1.21.6-fabric/src/main/kotlin/gg/essential/universal/utils/TemporaryTextureAllocator.kt
With 1.21.6 MC introduces a new gui renderer which now first collects all the quads/text/etc., sorts it into batches of similar type (while respecting ordering) and then draws those batches all at once (in the future even on a different thread).
Adapting UniversalCraft to this new paradigm isn't easy, since it's pretty much been ignoring the whole `DrawContext` concept so far. As such, for the time being, until we've designed a new universal gui rendering api, UScreen is now rendering exactly as it did before but to a temporary texture and then it submits that texture as a full-screen quad to MC's gui renderer.
=> Build: Port to 1.21.6 Fabric

src/main/java/gg/essential/universal/UGraphics.java
To render with a custom shadow color, which is not something Minecraft's builtin shadow rendering supports, we render the same text twice with the first time offset and colored to appear as the shadow. To render bold font, Minecraft draws each glyph twice with the second time offset by 1 horizontally to give the bold effect.
Prior to Minecraft 1.21.6, when no builtin shadow in involved (as is the case with our custom shadow rendering), both of these glyph rectangles had the exact same z value, and therefore all rectangles drawn for our shadow pass and our text pass all had the exact same z values. The default depth test function is LESS_EQUAL, so all rectangles were drawn based purely on the draw call order.
As of Minecraft 1.21.6 however, the vanilla text renderer now places the second …
=> UGraphics: Fix drawString with custom shadow color and bold font
